---
version: 2
checks:
  method-complexity:
    config:
      threshold: 7  # The default value for this is 5, we up it to 7 because validators require a bit more complexity
languages:
  Python: true
engines:
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false

ratings:
  paths:
  - "**.py"

exclude_paths:
  - "*/site-packages/*"
  - "**/tests/"
  - "**/migrations/"
